import Link from "next/link";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// import { TonConnectUIProvider } from '@tonconnect/ui-react'

import Layout from './components/Layout'

// Telegram Mini App SDK
import WebApp from '@twa-dev/sdk';

if (typeof window !== 'undefined') {
 // Hide the main button
 WebApp.MainButton.hide();
 // Expand the Telegram Mini App to full screen
 WebApp.expand();
 // Initialize the Telegram Mini App SDK
 WebApp.ready();
 // Enable the closing confirmation
 WebApp.enableClosingConfirmation();
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <nav className="p-4">
          <Link href="/">Home</Link> 
          | <Link href="/contact">Contact Us</Link> 
          | <Link href="/tonconnect">Ton Connect</Link>
        </nav>
      
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
